import type { FashionItem } from "@/types/fashion";

/**
 * Fallback items when Supabase has no data - so preview always shows something (Swiggy/Blinkit style).
 */
export const MOCK_FASHION_ITEMS: FashionItem[] = [
  {
    unique_id: "MOCK1",
    product_id: "M1",
    keyword_english: "Navy Blazer for Wedding",
    keyword_hindi: "शादी के लिए नेवी ब्लेज़र",
    keyword_hinglish: "wedding ke liye navy blazer",
    category: "Western Wear",
    sub_category: "Blazer",
    color_family: "Navy",
    hex_color: "#000080",
    hex_color_enhanced: "#000080",
    fabric: "Wool",
    occasion: "Wedding",
    body_type: "Regular",
    skin_tone: "Wheatish",
    confidence_level: "Safe",
    solves_problem: "Formal look",
    social_approval_score: { family: 5, friends: 5, professional: 5, dating: 4 },
    body_type_hack: "सभी body types पर suit करता है",
  },
  {
    unique_id: "MOCK2",
    product_id: "M2",
    keyword_english: "Maroon Kurta",
    keyword_hindi: "मैरून कुर्ता",
    keyword_hinglish: "maroon kurta",
    category: "Men's Wear",
    sub_category: "Kurta",
    color_family: "Maroon",
    hex_color: "#800000",
    hex_color_enhanced: "#800000",
    fabric: "Cotton",
    occasion: "Wedding",
    body_type: "Regular",
    skin_tone: "Wheatish",
    confidence_level: "Moderate",
    social_approval_score: { family: 5, friends: 5, professional: 4, dating: 5 },
    body_type_hack: "Wheatish skin pe bahut achha dikhta hai",
  },
  {
    unique_id: "MOCK3",
    product_id: "M3",
    keyword_english: "White Formal Shirt",
    keyword_hindi: "सफेद फॉर्मल शर्ट",
    keyword_hinglish: "white formal shirt",
    category: "Western Wear",
    sub_category: "Formal Shirt",
    color_family: "White",
    hex_color: "#FFFFFF",
    hex_color_enhanced: "#FFFFFF",
    fabric: "Cotton",
    occasion: "Formal",
    body_type: "Regular",
    skin_tone: "Wheatish",
    confidence_level: "Safe",
    social_approval_score: { family: 5, friends: 5, professional: 5, dating: 4 },
  },
  {
    unique_id: "MOCK4",
    product_id: "M4",
    keyword_english: "Olive Chinos",
    keyword_hindi: "ऑलिव चिनोस",
    keyword_hinglish: "olive chinos",
    category: "Western Wear",
    sub_category: "Chinos",
    color_family: "Olive",
    hex_color: "#556B2F",
    hex_color_enhanced: "#556B2F",
    fabric: "Cotton",
    occasion: "Casual",
    body_type: "Regular",
    skin_tone: "Wheatish",
    confidence_level: "Moderate",
    social_approval_score: { family: 4, friends: 5, professional: 4, dating: 5 },
  },
  {
    unique_id: "MOCK5",
    product_id: "M5",
    keyword_english: "Black Formal Shoes",
    keyword_hindi: "काले फॉर्मल जूते",
    keyword_hinglish: "black formal shoes",
    category: "Footwear",
    sub_category: "Formal Shoes",
    color_family: "Black",
    hex_color: "#000000",
    hex_color_enhanced: "#000000",
    fabric: "Leather",
    occasion: "Wedding",
    body_type: "Regular",
    skin_tone: "Wheatish",
    confidence_level: "Safe",
    social_approval_score: { family: 5, friends: 5, professional: 5, dating: 4 },
  },
  {
    unique_id: "MOCK6",
    product_id: "M6",
    keyword_english: "Cream Sherwani",
    keyword_hindi: "क्रीम शेरवानी",
    keyword_hinglish: "cream sherwani",
    category: "Men's Wear",
    sub_category: "Sherwani",
    color_family: "Cream",
    hex_color: "#FFFDD0",
    hex_color_enhanced: "#FFFDD0",
    fabric: "Silk",
    occasion: "Wedding",
    body_type: "Regular",
    skin_tone: "Wheatish",
    confidence_level: "Moderate",
    social_approval_score: { family: 5, friends: 5, professional: 4, dating: 5 },
  },
];
